spring:
  datasource:
    username: root
    password: zjz666666
    url: jdbc:mysql://localhost:3306/weixingorder?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    为了便于查询JSON数据，隐藏没有值的属性，减少流量的消耗，服务器不应该向客户端响应为null的属性！
#  jackson:
#    default-property-inclusion: non_null
  freemarker:
    cache: false
    suffix: .ftl

  redis:
    host: 192.168.1.27
    port: 6379

#开启驼峰命名转换
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mengzhiayuan.naruto.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#  应用的上下文路径，也可以称为项目路径，是构成url地址的一部分
server:
  servlet:
    context-path: /sell

wechat:
  # 公众账号, 授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付/商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  notifyUrl: http://mengzhiayuan.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://mengzhiayuan.natapp1.cc
  wechatOpenAuthorize: http://mengzhiayuan.natapp1.cc
  sell: http://lsx888.natapp1.cc

